settings:
  layout: grid
  columns: 4
  theme:
    background: '#37313a'
    textColor: '#f8fafc'
    cardBackground: '#1e293b'
    backgroundImage: /api/background/image
categories:
  - id: infra-01
    name: Infraestrutura
    apps:
      - id: pihole-01
        title: Pi-hole
        url: http://192.168.1.10/admin
        icon: simple-icons:pihole
        note: DNS Primário da Rede
        githubRepo: pi-hole/pi-hole
        dockerImage: pihole/pihole
  - id: b58cfaa3-d676-4773-a223-a595d0c43052
    name: Test Cat
    apps:
      - id: traefik-01
        title: Traefik
        url: http://192.168.1.10:8080
        icon: simple-icons:traefikproxy
        note: Reverse Proxy
        githubRepo: traefik/traefik
        dockerImage: traefik
